version: '3.1'
services:
  jartube:
    build: .
    environment:
        - MONGODB_URI=${MONGODB_URI}
    ports:
        - '8060:3000'
  database:
    image: 'mongo'
    restart: always
    container_name: mongoDB
    volumes:
      - jartube:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - '8061:27017'
volumes:
  jartube:
    external: true
